### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mabitbol** [simonsobs/fgspectra#11]
Accidentally installed with python 2 before switching environments to 3 and there is the warning:
  Found existing installation: fgspectra 0.1
    Can't uninstall 'fgspectra'. No files were found to uninstall.

FYI

**Comment by dpole** [comment]
OK, I think we can close this issue. If anybody encounters any installation problem, we'll have dedicated separate issue. Please reopen if there is anything still to be addressed or if you want to add details about how you solved this problem
