### ISSUE TITLE
kSZ has no SED dependence 

### ISSUE THREAD

**Issue by mabitbol** [simonsobs/fgspectra#14]
Need to add a constant / empty SED function so that kSZ works with the FactorizedCrossSpectrum?

**Comment by mabitbol** [comment]
Oh nvm I can just call the default SED class.

**Comment by mabitbol** [comment]
That didn't work.

**Comment by dpole** [comment]
You can use `ConstantSED`. However, I think that for kSZ (and possibly for CMB) it is better not to use any SED, and simpy add two dummy dimensions to the power spectrum to turn it into a frequency-frequency power spectrum. More explicitly, I'd change the shape as follows:

(ell, ) -> (1, 1, ell)

Broadcasting would operate as expected in any application I can think of.
