### ISSUE TITLE
General cross spectrum function

### ISSUE THREAD

**Issue by mabitbol** [simonsobs/fgspectra#15]
We'd like to have a function that takes the SED of X and Y and produces an SED of (X1*Y2 + X2*Y1) for the CorrelatedFactorizedCrossSpectrum class. But we need to be careful that things aren't going to be double counted (e.g. is there an issue when nu1=nu2?).

**Comment by mabitbol** [comment]
We don't want to have to write a cross spectrum SED for each potential correlated foreground signal that is factorizable is what I'm trying to get at. Instead we want to have a function that will do CrossSED(X,Y) for you. (I am thinking specifically about the frequency.tSZxCIB function in add_models_back_in branch. It's fine for now though glad it is working!)

**Comment by dpole** [comment]
I'm not clear about why you need that. `FactorizedCorrelatedComponent` is already supposed to compute it automatically.

**Comment by mabitbol** [comment]
I was thinking that we don't want to write a frequency.XxY function for every possible combination of correlated SEDs (e.g. all the potential galactic signals and any other extra-galactic correlations). If there not so many of these then it is ok to hand write them for now. Or maybe I am not understanding the usage of FactorizedCorrelatedComponent?

**Comment by dpole** [comment]
Ok, I propose that I push a commit containing the correlated CIB/tSZ, I open a PR and we discuss it there more concretely there (or in a call?)

**Comment by mabitbol** [comment]
Sounds good.

On 18 Apr 2019, at 17:24, Davide Poletti <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I propose that I push a commit containing the correlated CIB/tSZ, I open a PR and we discuss it there more concretely there (or in a call?)

**Comment by dpole** [comment]
#19 addresses this point and (too many) others.
Reporting here a relevant offline discussion while we create better documentation
![image](https://user-images.githubusercontent.com/4341327/58002678-47a80480-7adf-11e9-9736-1b98f27a66b5.png)
(Eq 12 only accounts for the correlated power)

let’s say, in a matrix A
whose first column is SZ
and the second is CIB
A C A^t is the result of CorrelatedFactorizedCrossSpectrum
where C is the component-component covariance matrix
if C is a 2x2 matrix made of only ones
you get
A C A^t = f f^t + mu mu^t + f mu^t + mu f^t
The last two terms are your Eq 12
