### ISSUE TITLE
tsz x cib

### ISSUE THREAD

**Issue by msyriac** [simonsobs/fgspectra#29]
I'm trying to get correlated tSZ x CIB following Zack's notebook: https://github.com/simonsobs/fgspectra/blob/master/notebooks/ACT_Models.ipynb

The output of 
```
# joint tSZ, CIB, and their correlation
        tSZ_and_CIB(
            {'kwseq': (
                {'nu':freqs, 'nu_0':par['nu_0']},
                {'nu': freqs, 'nu_0':par['nu_0'], 'temp':par['T_d'], 'beta':par['beta_c']} 
                )},
            {'kwseq': ( 
                {'ell':ells, 'ell_0':par['ell_0'], 
                 'amp':par['a_tSZ']},
                {'ell':ells, 'ell_0':par['ell_0'], 
                 'alpha':2-par['n_CIBC'], 'amp':par['a_c']},
                {'ell':ells, 'ell_0':par['ell_0'], 
                 'amp': -par['xi'] * np.sqrt(par['a_tSZ'] * par['a_c'])}
                )})
```

however seems to be a tuple with one element whose shape is `(1, 2998)` where I've asked for 2998 multipoles. Shouldn't this be at least a (2,2,2998) array? @xzackli

**Comment by dpole** [comment]
Hi Mat, it is because in that example Zack construct the contributions of the two components individually. I think that the functionality you are looking for is

https://github.com/simonsobs/fgspectra/blob/161a61b32998a4224b50e76382f9b7ff8dd8388d/fgspectra/power.py#L331

**Comment by xzackli** [comment]
Consider equation 11 of [Dunkley et al. 2013](https://arxiv.org/pdf/1301.0776.pdf),

![image](https://user-images.githubusercontent.com/8048811/74566443-773a4f00-4f41-11ea-92f7-ca05cc390e9d.png)

where the function _f'_ is 

![image](https://user-images.githubusercontent.com/8048811/74566299-2f1b2c80-4f41-11ea-9619-b4874f062edb.png)

Mat wants to get this function B from fgspectra, for a given frequency. It is already effectively computed inside the tSZ_and_CIB object Mat mentioned. Perhaps a utility function for doing this?

Note that in the unit test I wrote validating our implementation against the old ACT Fortran likelihood, I had to extract this function as well. I just subtracted the [autos](https://github.com/simonsobs/fgspectra/blob/master/tests/test_models.py#L124).

**Comment by xzackli** [comment]
The function `SZxCIB_Addison2012(PowerSpectraAndCovariance)` in `power.py` will give Mat the right shape of the power spectrum, but doesn't have the frequency normalization.

**Comment by dpole** [comment]
This is probably related to #26 
What is the use of this function beyond plotting?
Depending on the answer, we may decide to implement a utility class similar to FactorizedCrossSpectrum that takes two SED instead of one and scales one frequency dimension with the first and the other with the second.

**Comment by xzackli** [comment]
I think the main use is for Gaussian realizations to i.e. test component separation codes. For example, if I want to generate a Gaussian sim of tSZ and CIB, then for every multipole I need to supply the tSZ x tSZ, CIB x CIB, and the cross-term tSZ x CIB.

**Comment by dpole** [comment]
This is the part I don't understand. If you just care about the frequency maps, why can't you use directly the `(freq, freq, ell)` output?

**Comment by xzackli** [comment]
Right -- the total cross power spectra of the foreground components is the _true observable_ and we never actually measure i.e. the true CIB-only map. But wouldn't it be cool if MBS could do something like Gaussian realizations of

* **Input:** some kind of modeling i.e. like fgspectra templates
* **Output:** a set of frequency maps for each foreground component

So for example, I might simulate this set of maps, and I'd add the foreground components together for each frequency to test my multifrequency likelihood. But I also have the true maps for each component! The most immediate use I can see is for evaluating how different component separation methods perform.

If I take a cross-spectrum between i.e. the outputted tSZ map and the CIB map at the same frequency, I should recover the fgspectra input. For that to have happened, we must have somehow passed that cross-component power. 

@msyriac

**Comment by msyriac** [comment]
Exactly what Zack said. It would be silly if we had to maintain an entirely separate library that lets a science explorer **quickly** answer questions like:
1. What is the tSZ power spectrum contribution at 90 GHz?
2. What is the correlation between the tSZ and CIB at 150 GHz?
3. Give me the tSZ, CIB cross and auto powers at 90 and 150 GHz, so I can generate some Gaussian realizations of them.
4. What is the radio power at 220 GHz given a flux cut of 5 mJy?
...etc.

These are already available deep inside the code somewhere, and all we need is to expose a separate API for it -- we don't need to make any changes to the existing function calls. In other words, we need wrappers that let us get individual component power spectra. These calls are routinely made when **testing** and deploying lensing reconstruction, component separation, likelihoods and mini-science-analyses. We definitely don't want to be in a position where we just have some ASCII file that has the sum of all the foreground powers for some frequency band selection.

**Comment by dpole** [comment]
Please have a look at my PR #31 and let me know if it provides the feature you're asking for. Note that 

https://github.com/simonsobs/fgspectra/blob/4b84adab44419c05b502af755867c712089bde3f/fgspectra/cross.py#L250

inherits the new method

https://github.com/simonsobs/fgspectra/blob/4b84adab44419c05b502af755867c712089bde3f/fgspectra/cross.py#L187

Thanks @xzackli and @msyriac for the extra info. I now see better the relevance of a handy API for the `(comp, comp, freq, freq, ell)` tensor. Let me emphasize a couple of probably obvious things

1. My patch applies only to components that inherit from `CorrelatedFactorizedCrossSpectrum`. That means we have to code all the combination of components of which we want to evaluate the correlations.
2. For simulation purposes, we can keep using `eval` (which gives directly the `(freq, freq, ell)` tensor)

Please let me know any comment about the API, if the naming is sufficiently intuitive and if the docstrings are clear

**Comment by dpole** [comment]
Oh! now I see why we created #31 
Please give it a look and let me know if it does what you needed

**Comment by msyriac** [comment]
Yep, I think this helps! Can close.
