### ISSUE TITLE
Make fgspectra installable via pip

### ISSUE THREAD

**Issue by itrharrison** [simonsobs/fgspectra#50]
Hi!

We are hoping to package SOLikeT for PyPI in the next few weeks, but at the moment we are dependent on fgspectra for the foregrounds. At the moment our requirements.txt points to a specfic branch on the github repo:
`fgspectra @ git+https://github.com/simonsobs/fgspectra@act_sz_x_cib#egg=fgspectra`

For SOLikeT to go on PyPI having requirements like this is forbidden, though. We could solve this by having fgspectra on PyPI too so the depedency just becomes `fgspectra`.

Would you be able to do this? Or if we do it would you accept the PR? Or some combination?

**Comment by xzackli** [comment]
@itrharrison @xgarrido yes, is it ok if this happens no later than Monday of next week? I'd like to tag a 1.0 and then put register it on pip, but I must learn how to do python packaging in 2023. This will fix the main problems with merging active pull requests, as then I can work on a breaking release tagged as 2.x.

**Comment by itrharrison** [comment]
@xzackli great! Thank you! Feel free to tag me in to anything I can help with (reviews etc) and maybe @HTJense and @sgiardie too.

**Comment by xzackli** [comment]
This has been implemented, and the previous `act_sz_x_cib` is now the main branch and is tagged v1.0.0 on PyPI. You can install it with `pip install fgspectra`.

This is a breaking release from the previous `master` branch of fgspectra, which has also been uploaded and tagged 0.1.0.

**Comment by itrharrison** [comment]
@xzackli excellent, thank you very much!
