### ISSUE TITLE
Update pkg_resources

### ISSUE THREAD

**Issue by cmbant** [simonsobs/fgspectra#56]
Currently get deprecation warnings - switch to importlib.resources

**Comment by HTJense** [comment]
I tried to fix this but I do not have permissions for the repository.

It is luckily quite simple: in [this](https://github.com/simonsobs/fgspectra/blob/main/fgspectra/power.py) file, the `pkg_resources` import and function call in line 19 need to be replaced by:

`data_path = importlib.resources.files("fgspectra") / "data"`

@xzackli @beringueb can perhaps address this.

**Comment by beringueb** [comment]
Thanks for the suggestion @HTJense, will do a PR later today.
